user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 1313;
        server_name localhost;

        location / {
            root /home/static;
            index index.html index.htm;
            # Add rules like this
            # if ($query_string = "p=2") {
            #    return 302 /about/;
            # }
            
            if ($query_string = "p=6029") { return 302 /2022/07/07/oci-checklist/; }
            if ($query_string = "p=5454") { return 302 /2021/08/23/a-tale-of-crashing-web-app-and-failing-crash-dump-collection-tools/; }
            if ($query_string = "page_id=5424") { return 302 /sitecore/; }
        }
    }
}
